### ISSUE TITLE
‘PyString_FromString’ was not declared in this scope

### ISSUE THREAD

**Issue by ahopkins** [rlguy/FantasyMapGenerator#1]
I was trying to install your package, but when running `make` I encountered the following.

    /my/path/FantasyMapGenerator/src/render.cpp: In function ‘void gen::render::drawMap(std::vector<char>&, std::__cxx11::string)’:
    /my/path/FantasyMapGenerator/src/render.cpp:17:75: error: ‘PyString_FromString’ was not declared in this scope
         PyObject *pFunctionName = PyString_FromString(drawFunctionName.c_str());
                                                                               ^
    CMakeFiles/objects.dir/build.make:254: recipe for target 'CMakeFiles/objects.dir/src/render.cpp.o' failed
    make[2]: *** [CMakeFiles/objects.dir/src/render.cpp.o] Error 1
    CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/objects.dir/all' failed
    make[1]: *** [CMakeFiles/objects.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2

Any thoughts on resolving?

**Comment by ahopkins** [comment]
Issue resolved. I ran it inside a virtual environment with python 3 instead of legacy python, and all is well.

**Comment by ri0t** [comment]
I don't think this resolves the issue (yeah, i'm a hard-switch-to-3 advocate), but i'm also not exactly proficient in what exactly is going awry here. I am missing a (cmake?) argument to make sure which interpreter is used.
The system chose 3.6 here by default (without any venv, running it within a 2.7 venv doesn't help!) - so either the code should work with that or the default selection is bad and should've announce the problem :)

**Comment by rlguy** [comment]
I have looked into this. I have found that in Python3, the _PyString_FromString_ method was updated to _PyBytes_FromString_. In Python3.2+ the _PyString_FromString_ method was removed. I have updated the repository to choose the correct method depending on which Python interpreter CMake selects.

I hope this resolves the issue.
